const x = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 1,
      id: 2426851,
      known_for_department: "Acting",
      name: "Clara Stack",
      original_name: "Clara Stack",
      popularity: 39.8737,
      profile_path: "/p9WHUjES7qsi2O9pO04AhLaDdms.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/2fOKVDoc2O3eZmBZesWPuE5kgPN.jpg",
          id: 200875,
          name: "IT: Welcome to Derry",
          original_name: "IT: Welcome to Derry",
          overview:
            "In 1962, a couple with their son move to Derry, Maine just as a young boy disappears. With their arrival, very bad things begin to happen in the town.",
          poster_path: "/nyy3BITeIjviv6PFIXtqvc8i6xi.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18, 9648],
          popularity: 398.3767,
          first_air_date: "2025-10-26",
          vote_average: 8,
          vote_count: 481,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/gOJJjBB1aj6vqzuJLspERcwZuPQ.jpg",
          id: 936059,
          title: "The Naughty Nine",
          original_title: "The Naughty Nine",
          overview:
            "Fifth-grader Andy finds himself without a present from Santa on Christmas morning. Realizing he must have landed on the “naughty list” and feeling unfairly maligned, Andy pulls together a team of eight other naughty-listers to help him execute an elaborate heist on Santa’s Village at the North Pole to get the presents they feel they deserve.",
          poster_path: "/5JoTI5Nrh2U639WfwUk0Akum7fQ.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10751, 12, 35, 10770, 80],
          popularity: 6.5623,
          release_date: "2023-11-09",
          video: false,
          vote_average: 6.3,
          vote_count: 76,
        },
        {
          adult: false,
          backdrop_path: "/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg",
          id: 88329,
          name: "Hawkeye",
          original_name: "Hawkeye",
          overview:
            "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero. The two are forced to work together when a presence from Barton’s past threatens to derail far more than the festive spirit.",
          poster_path: "/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18, 35, 10759],
          popularity: 19.6288,
          first_air_date: "2021-11-24",
          vote_average: 7.8,
          vote_count: 3571,
          origin_country: ["US"],
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 4676098,
      known_for_department: "Acting",
      name: "Candy Veloso",
      original_name: "Candy Veloso",
      popularity: 29.4936,
      profile_path: "/uW04svzRyG6gHDEqydUmWQb5iK8.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/uUJuPiZh1QfIeTa1GeLWqnEkaP2.jpg",
          id: 1302011,
          title: "Init",
          original_title: "Init",
          overview:
            "When a young barrio lass moves in to the city to study, she lives in a boarding house with other college students. Unknown to them, behind her shy and timid personality is a woman with insatiable hunger for sex.",
          poster_path: "/fGY13rtdRzFqTkDMi5JayUWg6vL.jpg",
          media_type: "movie",
          original_language: "tl",
          genre_ids: [18],
          popularity: 6.2856,
          release_date: "2024-07-30",
          video: false,
          vote_average: 5.8,
          vote_count: 9,
        },
        {
          adult: false,
          backdrop_path: "/vxsCqREokzkRQMQXZRmvjsQzpd7.jpg",
          id: 1337404,
          title: "Tahong",
          original_title: "Tahong",
          overview:
            "Mira, the daughter of a mussel farmer who needs to fight a reclamation project. She would do everything to save their livelihood even if it means sacrificing her innocence.",
          poster_path: "/nvvb92EslVzouKKcw4xbUHN6vS8.jpg",
          media_type: "movie",
          original_language: "tl",
          genre_ids: [18],
          popularity: 5.5807,
          release_date: "2024-10-04",
          video: false,
          vote_average: 5,
          vote_count: 3,
        },
        {
          adult: false,
          backdrop_path: "/jNp6Ql2OiinZBdtOZg5RaDxwY73.jpg",
          id: 1280461,
          title: "Dirty Ice Cream",
          original_title: "Dirty Ice Cream",
          overview:
            "Villagers are experiencing an extreme heat. Two hot ice cream vendors come to the village to sell ice cream. With electricity out, the women of the subdivision take turns having the vendors satisfy their every needs.",
          poster_path: "/qrD5DuwYuzdwcT5MAeopA4vZfIN.jpg",
          media_type: "movie",
          original_language: "tl",
          genre_ids: [18],
          popularity: 4.9322,
          release_date: "2024-05-10",
          video: false,
          vote_average: 5.3,
          vote_count: 10,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 1245,
      known_for_department: "Acting",
      name: "Scarlett Johansson",
      original_name: "Scarlett Johansson",
      popularity: 29.3152,
      profile_path: "/mjReG6rR7NPMEIWb1T4YWtV11ty.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/ozVwXlfxqNsariipatGwa5px3Pm.jpg",
          id: 240832,
          title: "Lucy",
          original_title: "Lucy",
          overview:
            "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
          poster_path: "/dhjyfcwEoW6jJ4Q7DpZTp6E58GA.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878],
          popularity: 10.8175,
          release_date: "2014-07-25",
          video: false,
          vote_average: 6.5,
          vote_count: 16678,
        },
        {
          adult: false,
          backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
          id: 497698,
          title: "Black Widow",
          original_title: "Black Widow",
          overview:
            "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
          poster_path: "/7JPpIjhD2V0sKyFvhB9khUMa30d.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 12, 878],
          popularity: 10.2277,
          release_date: "2021-07-07",
          video: false,
          vote_average: 7.2,
          vote_count: 10858,
        },
        {
          adult: false,
          backdrop_path: "/dDVqfmCzSy3TKSmiS2pJ9QB5E3P.jpg",
          id: 315837,
          title: "Ghost in the Shell",
          original_title: "Ghost in the Shell",
          overview:
            "In the near future, Major is the first of her kind: a human saved from a terrible crash, then cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.",
          poster_path: "/zCtL3UBgCoZzd7XTVGhvl6XY75E.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 18, 28],
          popularity: 5.3441,
          release_date: "2017-03-29",
          video: false,
          vote_average: 6.1,
          vote_count: 8353,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 18050,
      known_for_department: "Acting",
      name: "Elle Fanning",
      original_name: "Elle Fanning",
      popularity: 27.431,
      profile_path: "/e8CUyxQSE99y5IOfzSLtHC0B0Ch.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/4hfcpHmMEgmFTdnVx4XCtM6dgCG.jpg",
          id: 102651,
          title: "Maleficent",
          original_title: "Maleficent",
          overview:
            "A beautiful, pure-hearted young woman, Maleficent has an idyllic life growing up in a peaceable forest kingdom, until one day when an invading army threatens the harmony of the land. She rises to be the land's fiercest protector, but she ultimately suffers a ruthless betrayal – an act that begins to turn her heart into stone. Bent on revenge, Maleficent faces an epic battle with the invading King's successor and, as a result, places a curse upon his newborn infant Aurora. As the child grows, Maleficent realizes that Aurora holds the key to peace in the kingdom – and to Maleficent's true happiness as well.",
          poster_path: "/bDG3yei6AJlEAK3A5wN7RwFXQ7V.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [14, 12, 28, 10751, 10749],
          popularity: 9.7626,
          release_date: "2014-05-28",
          video: false,
          vote_average: 7.1,
          vote_count: 13480,
        },
        {
          adult: false,
          backdrop_path: "/xcfjWEmSpgJe8htlg1qFTwQfPG7.jpg",
          id: 301365,
          title: "The Neon Demon",
          original_title: "The Neon Demon",
          overview:
            "When aspiring model Jesse moves to Los Angeles, her youth and vitality are devoured by a group of beauty-obsessed women who will take any means necessary to get what she has.",
          poster_path: "/3rBo2AfWSlvsPmYFdJsNUMfkNIo.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 53],
          popularity: 5.3129,
          release_date: "2016-05-31",
          video: false,
          vote_average: 6.5,
          vote_count: 3844,
        },
        {
          adult: false,
          backdrop_path: "/x6Dr9i6vhWICxs7hnX2BakcMtPd.jpg",
          id: 37686,
          title: "Super 8",
          original_title: "Super 8",
          overview:
            "In late 1970s Ohio, a group of friends filming a homemade zombie movie witness a devastating train derailment. Soon after, their quiet town is gripped by unexplained disappearances, strange phenomena, and a growing sense of fear, as they uncover that something terrifying has been set loose.",
          poster_path: "/pUWIjaMMYJjeBm5bJyE3mIXdQ62.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [53, 878, 9648],
          popularity: 7.6042,
          release_date: "2011-06-08",
          video: false,
          vote_average: 6.8,
          vote_count: 6862,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 18897,
      known_for_department: "Acting",
      name: "Jackie Chan",
      original_name: "成龍",
      popularity: 22.8366,
      profile_path: "/nraZoTzwJQPHspAVsKfgl3RXKKa.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/ivGXj9i01x5FECAikQkP4X5ojmY.jpg",
          id: 2109,
          title: "Rush Hour",
          original_title: "Rush Hour",
          overview:
            "When Hong Kong Inspector Lee is summoned to Los Angeles to investigate a kidnapping, the FBI doesn't want any outside help and assigns cocky LAPD Detective James Carter to distract Lee from the case. Not content to watch the action from the sidelines, Lee and Carter form an unlikely partnership and investigate the case themselves.",
          poster_path: "/we7wOLVFgxhzLzUt0qNe50xdIQZ.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 35, 80],
          popularity: 8.3756,
          release_date: "1998-09-18",
          video: false,
          vote_average: 7.059,
          vote_count: 5391,
        },
        {
          adult: false,
          backdrop_path: "/vPJwn9pp5f58CqdaXU3eOSLoJkl.jpg",
          id: 5175,
          title: "Rush Hour 2",
          original_title: "Rush Hour 2",
          overview:
            "It's vacation time for Carter as he finds himself alongside Lee in Hong Kong wishing for more excitement. While Carter wants to party and meet the ladies, Lee is out to track down a Triad gang lord who may be responsible for killing two men at the American Embassy. Things get complicated as the pair stumble onto a counterfeiting plot. The boys are soon up to their necks in fist fights and life-threatening situations. A trip back to the U.S. may provide the answers about the bombing, the counterfeiting, and the true allegiance of sexy customs agent Isabella.",
          poster_path: "/nmllsevWzx7XtrlARs3hHJn5Pf.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 35, 80],
          popularity: 7.5997,
          release_date: "2001-08-03",
          video: false,
          vote_average: 6.8,
          vote_count: 4395,
        },
        {
          adult: false,
          backdrop_path: "/ozsLB1HRCN6ZAmJN89pWtoiAwnb.jpg",
          id: 5174,
          title: "Rush Hour 3",
          original_title: "Rush Hour 3",
          overview:
            "After a botched assassination attempt, the mismatched duo finds themselves in Paris, struggling to retrieve a precious list of names, as the murderous crime syndicate's henchmen try their best to stop them. Once more, Lee and Carter must fight their way through dangerous gangsters; however, this time, the past has come back to haunt Lee. Will the boys get the job done once and for all?",
          poster_path: "/rZ7IxJlPhNNJ6Rn8z1rzsXuA70P.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 35, 80],
          popularity: 8.252,
          release_date: "2007-08-08",
          video: false,
          vote_average: 6.5,
          vote_count: 3549,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 1646,
      known_for_department: "Acting",
      name: "Udo Kier",
      original_name: "Udo Kier",
      popularity: 22.6827,
      profile_path: "/ppWw8WpcibWGLVSFODvwIaWhurk.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/hZnnUq0mrUQ3e54SJVca4mf2oAQ.jpg",
          id: 36647,
          title: "Blade",
          original_title: "Blade",
          overview:
            'The Daywalker known as "Blade" - a half-vampire, half-mortal man - becomes the protector of humanity against an underground army of vampires.',
          poster_path: "/hx0sdduAsr4rq03RZKZzglR25z7.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 28],
          popularity: 7.6189,
          release_date: "1998-08-21",
          video: false,
          vote_average: 6.8,
          vote_count: 6434,
        },
        {
          adult: false,
          backdrop_path: "/9i478egHXEwnO0zbDYQLt4AtGb5.jpg",
          id: 3049,
          title: "Ace Ventura: Pet Detective",
          original_title: "Ace Ventura: Pet Detective",
          overview:
            "He's Ace Ventura: Pet Detective. Jim Carrey is on the case to find the Miami Dolphins' missing mascot and quarterback Dan Marino. He goes eyeball to eyeball with a man-eating shark, stakes out the Miami Dolphins and woos and wows the ladies. Whether he's undercover, under fire or underwater, he always gets his man… or beast!",
          poster_path: "/pqiRuETmuSybfnVZ7qyeoXhQyN1.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 9648, 80],
          popularity: 5.9115,
          release_date: "1994-02-04",
          video: false,
          vote_average: 6.6,
          vote_count: 6127,
        },
        {
          adult: false,
          backdrop_path: "/rtr0l61RxLPkmZHbZj0WFlGx5G5.jpg",
          id: 301337,
          title: "Downsizing",
          original_title: "Downsizing",
          overview:
            "A kindly occupational therapist undergoes a new procedure to be shrunken to four inches tall so that he and his wife can help save the planet and afford a nice lifestyle at the same time.",
          poster_path: "/5bNzInSSAXfr0MFlHfb4IoQePVx.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 878, 35],
          popularity: 3.1541,
          release_date: "2017-12-22",
          video: false,
          vote_average: 5.4,
          vote_count: 3980,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 5081,
      known_for_department: "Acting",
      name: "Emily Blunt",
      original_name: "Emily Blunt",
      popularity: 22.2702,
      profile_path: "/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/nIrDm42dy5PaXtUAzUfPmxM4mQm.jpg",
          id: 447332,
          title: "A Quiet Place",
          original_title: "A Quiet Place",
          overview:
            "A family is forced to live in silence while hiding from creatures that hunt by sound.",
          poster_path: "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 18, 878],
          popularity: 7.2381,
          release_date: "2018-04-03",
          video: false,
          vote_average: 7.4,
          vote_count: 14902,
        },
        {
          adult: false,
          backdrop_path: "/fKPgObonYgPgCdu88yjV7Hpn7Dp.jpg",
          id: 273481,
          title: "Sicario",
          original_title: "Sicario",
          overview:
            "An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.",
          poster_path: "/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 80, 53],
          popularity: 8.6409,
          release_date: "2015-09-17",
          video: false,
          vote_average: 7.4,
          vote_count: 9187,
        },
        {
          adult: false,
          backdrop_path: "/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg",
          id: 137113,
          title: "Edge of Tomorrow",
          original_title: "Edge of Tomorrow",
          overview:
            "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
          poster_path: "/nBM9MMa2WCwvMG4IJ3eiGUdbPe6.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878],
          popularity: 9.1512,
          release_date: "2014-05-27",
          video: false,
          vote_average: 7.632,
          vote_count: 14568,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 115440,
      known_for_department: "Acting",
      name: "Sydney Sweeney",
      original_name: "Sydney Sweeney",
      popularity: 20.5036,
      profile_path: "/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg",
          id: 85552,
          name: "Euphoria",
          original_name: "Euphoria",
          overview:
            "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
          poster_path: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18],
          popularity: 36.3287,
          first_air_date: "2019-06-16",
          vote_average: 8.3,
          vote_count: 10213,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg",
          id: 1072790,
          title: "Anyone But You",
          original_title: "Anyone But You",
          overview:
            "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
          poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10749, 35],
          popularity: 10.344,
          release_date: "2023-12-21",
          video: false,
          vote_average: 6.8,
          vote_count: 2798,
        },
        {
          adult: false,
          backdrop_path: "/3zKU2EznBtOPtheyCTQwdZL4b93.jpg",
          id: 1041613,
          title: "Immaculate",
          original_title: "Immaculate",
          overview:
            "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
          poster_path: "/zyopv7D5j7cfswG0NYiA14qAdPC.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 9648, 53],
          popularity: 4.8494,
          release_date: "2024-03-20",
          video: false,
          vote_average: 6.225,
          vote_count: 1514,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 2034418,
      known_for_department: "Acting",
      name: "Jacob Elordi",
      original_name: "Jacob Elordi",
      popularity: 19.0004,
      profile_path: "/lC9pK3ADyPpH4dRo2BKZBaTZPfu.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg",
          id: 85552,
          name: "Euphoria",
          original_name: "Euphoria",
          overview:
            "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
          poster_path: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18],
          popularity: 36.3287,
          first_air_date: "2019-06-16",
          vote_average: 8.3,
          vote_count: 10213,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/bXdCpL1A1mW2sEBiTmYYFnb10XN.jpg",
          id: 583083,
          title: "The Kissing Booth 2",
          original_title: "The Kissing Booth 2",
          overview:
            "With college decisions looming, Elle juggles her long-distance romance with Noah, changing relationship with bestie Lee and feelings for a new classmate.",
          poster_path: "/mb7wQv0adK3kjOUr9n93mANHhPJ.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 10749],
          popularity: 7.5951,
          release_date: "2020-07-24",
          video: false,
          vote_average: 7.6,
          vote_count: 5078,
        },
        {
          adult: false,
          backdrop_path: "/aqrDUkuzksLhOD8pbyBXLO0dz5t.jpg",
          id: 454983,
          title: "The Kissing Booth",
          original_title: "The Kissing Booth",
          overview:
            "When teenager Elle's first kiss leads to a forbidden romance with the hottest boy in high school, she risks her relationship with her best friend.",
          poster_path: "/vcQNnnXgKLacoYF4LNWgkNiDXPd.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10749, 35],
          popularity: 7.7373,
          release_date: "2018-05-11",
          video: false,
          vote_average: 7.17,
          vote_count: 7360,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 974169,
      known_for_department: "Acting",
      name: "Jenna Ortega",
      original_name: "Jenna Ortega",
      popularity: 18.1426,
      profile_path: "/cV4x7jNmsGLdKZn5I6xVF3Ltnmg.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
          id: 119051,
          name: "Wednesday",
          original_name: "Wednesday",
          overview:
            "Smart, sarcastic and a little dead inside, Wednesday Addams investigates twisted mysteries while making new friends — and foes — at Nevermore Academy.",
          poster_path: "/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [10765, 9648, 35],
          popularity: 68.6848,
          first_air_date: "2022-11-23",
          vote_average: 8.4,
          vote_count: 10063,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg",
          id: 760104,
          title: "X",
          original_title: "X",
          overview:
            "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.",
          poster_path: "/lopZSVtXzhFY603E9OqF7O1YKsh.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 53],
          popularity: 12.2168,
          release_date: "2022-03-17",
          video: false,
          vote_average: 6.735,
          vote_count: 3733,
        },
        {
          adult: false,
          backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
          id: 646385,
          title: "Scream",
          original_title: "Scream",
          overview:
            "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
          poster_path: "/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [27, 9648],
          popularity: 8.919,
          release_date: "2022-01-12",
          video: false,
          vote_average: 6.7,
          vote_count: 3619,
        },
      ],
    },
    {
      adult: false,
      gender: 0,
      id: 583104,
      known_for_department: "Acting",
      name: "Gregorio Acosta",
      original_name: "Gregorio Acosta",
      popularity: 18.0215,
      profile_path: null,
      known_for: [
        {
          adult: false,
          backdrop_path: "/uktYTQIcf5I7xyJHgrXXWJNQJU5.jpg",
          id: 32068,
          title: "The Scalphunters",
          original_title: "The Scalphunters",
          overview:
            "Forced to trade his valuable furs for a well-educated escaped slave, a rugged trapper vows to recover the pelts from the Indians and later the renegades that killed them.",
          poster_path: "/m82aMr1Pcqt5t0cpSCwq5REdajY.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 37],
          popularity: 6.1352,
          release_date: "1968-02-29",
          video: false,
          vote_average: 6.4,
          vote_count: 112,
        },
        {
          adult: false,
          backdrop_path: "/akRrqnWtdcUTotBalfmpUoTktwm.jpg",
          id: 46757,
          title: "The Last Sunset",
          original_title: "The Last Sunset",
          overview:
            "At a Mexican ranch, fugitive O'Malley and pursuing Sheriff Stribling agree to help rancher Breckenridge drive his herd into Texas where Stribling could legally arrest O'Malley, but Breckenridge's wife complicates things.",
          poster_path: "/ixhQwzGbyG7AYAHgvnwzAIxwMnH.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [37, 18],
          popularity: 3.2384,
          release_date: "1961-06-08",
          video: false,
          vote_average: 6.794,
          vote_count: 90,
        },
        {
          adult: false,
          backdrop_path: "/oNAf3P2qxcQp02AmcZJvOiHNMsI.jpg",
          id: 41300,
          title: "Si yo fuera diputado",
          original_title: "Si yo fuera diputado",
          overview:
            "Cantinflas is a unique barber, who trades with an elderly neighbor, a lawyer by profession, laws lessons in exchange for haircuts and shaved. It proposes advice to defend in court the disadvantaged neighborhood. His success deputy seeks the votes as the other candidate, Don Próculo, it is not accepted by anyone but his own bodyguards. Don Próculo will use know how much ruse to win the election by the Council, and also for the love of 'Sarita'",
          poster_path: "/fvIIl8VFhbn60jLRN0ZDP8jMo80.jpg",
          media_type: "movie",
          original_language: "es",
          genre_ids: [35],
          popularity: 2.2245,
          release_date: "1952-01-30",
          video: false,
          vote_average: 7.4,
          vote_count: 72,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 3995419,
      known_for_department: "Acting",
      name: "Tom Wozniczka",
      original_name: "Tom Wozniczka",
      popularity: 17.9141,
      profile_path: "/9qrW3utGsmeJ1iJVPPZx2SDyhaH.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/pzw13NVDnsPqH62yOHuyxJFAmrS.jpg",
          id: 218961,
          name: "Drops of God",
          original_name: "Les Gouttes de Dieu",
          overview:
            "While the world of wine mourns the death of Alexandre Léger, his estranged daughter, Camille, learns his extraordinary collection is now hers. But before she can claim her inheritance, Camille must best Alexandre's protégé, Issei, in a test of their senses.",
          poster_path: "/9VxIqKXkgVWTZ1y5c3sKQQi6NvO.jpg",
          media_type: "tv",
          original_language: "fr",
          genre_ids: [18, 9648],
          popularity: 3.2984,
          first_air_date: "2023-04-21",
          vote_average: 7.5,
          vote_count: 114,
          origin_country: ["FR"],
        },
        {
          adult: false,
          backdrop_path: "/bDfboQUb45Cv9MYyVBDZw8M8xSM.jpg",
          id: 95480,
          name: "Slow Horses",
          original_name: "Slow Horses",
          overview:
            "Follow a dysfunctional team of MI5 agents—and their obnoxious boss, the notorious Jackson Lamb—as they navigate the espionage world's smoke and mirrors to defend England from sinister forces.",
          poster_path: "/dnpatlJrEPiDSn5fzgzvxtiSnMo.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [80, 18, 35],
          popularity: 36.7995,
          first_air_date: "2022-04-01",
          vote_average: 7.989,
          vote_count: 697,
          origin_country: ["GB"],
        },
        {
          adult: false,
          backdrop_path: "/4FzoxZAJnhpoeYHexQCHorsWLxB.jpg",
          id: 1323475,
          title: "Champagne Problems",
          original_title: "Champagne Problems",
          overview:
            "A driven American exec heads to Paris determined to acquire a champagne brand by Christmas — and accidentally falls for the heir to the bubbly empire.",
          poster_path: "/a66w2eVNFHMgevJlw0d6f4TTrrD.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [10749, 35],
          popularity: 54.1954,
          release_date: "2025-11-18",
          video: false,
          vote_average: 6.2,
          vote_count: 52,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 1649246,
      known_for_department: "Acting",
      name: "Lilah Richcreek Estrada",
      original_name: "Lilah Richcreek Estrada",
      popularity: 17.6765,
      profile_path: "/pA3pPpC5ShWvoqREeHLpScXd2Qg.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/6EObfIe4akZGvCLXwXLJw3kPitQ.jpg",
          id: 245312,
          name: "A Man on the Inside",
          original_name: "A Man on the Inside",
          overview:
            "A retired professor with a knack for snooping gets a new lease on life when a private investigator recruits him to go undercover and crack a case.",
          poster_path: "/c09XdTLpLku2tqHt158NZBgC4hi.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [35, 80],
          popularity: 41.9614,
          first_air_date: "2024-11-21",
          vote_average: 7.5,
          vote_count: 154,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/uJFQayf3WqxIbS1drH5dTUx57Ph.jpg",
          id: 2691,
          name: "Two and a Half Men",
          original_name: "Two and a Half Men",
          overview:
            "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
          poster_path: "/xgfjxyV3g1S68opzuvG6G87muDp.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [35],
          popularity: 66.4186,
          first_air_date: "2003-09-22",
          vote_average: 7.4,
          vote_count: 3508,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/u04AvxFIDgL9JSd9xoVNK3BoBEd.jpg",
          id: 39340,
          name: "2 Broke Girls",
          original_name: "2 Broke Girls",
          overview:
            "Comedy about the unlikely friendship that develops between two very different young women who meet waitressing at a diner in trendy Williamsburg, Brooklyn, and form a bond over one day owning their own successful cupcake business. Only one thing stands in their way – they’re broke.",
          poster_path: "/wW1SDEoZ6pDfnSkVQuXwOo8ICep.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [35],
          popularity: 27.8451,
          first_air_date: "2011-09-19",
          vote_average: 7.203,
          vote_count: 1641,
          origin_country: ["US"],
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 976,
      known_for_department: "Acting",
      name: "Jason Statham",
      original_name: "Jason Statham",
      popularity: 17.3511,
      profile_path: "/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/gTghF8ardwJ48XLHkiapWk3ZmSo.jpg",
          id: 107,
          title: "Snatch",
          original_title: "Snatch",
          overview:
            "Unscrupulous boxing promoters, violent bookies, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewellers fight to track down a priceless stolen diamond.",
          poster_path: "/kJZoAHq1SLDdWjeNGtlHAnGpmFV.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [80, 35],
          popularity: 9.4592,
          release_date: "2000-09-01",
          video: false,
          vote_average: 7.817,
          vote_count: 9594,
        },
        {
          adult: false,
          backdrop_path: "/ibKeXahq4JD63z6uWQphqoJLvNw.jpg",
          id: 345940,
          title: "The Meg",
          original_title: "The Meg",
          overview:
            "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
          poster_path: "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878, 27],
          popularity: 7.2206,
          release_date: "2018-08-09",
          video: false,
          vote_average: 6.2,
          vote_count: 7991,
        },
        {
          adult: false,
          backdrop_path: "/70AV2Xx5FQYj20labp0EGdbjI6E.jpg",
          id: 637649,
          title: "Wrath of Man",
          original_title: "Wrath of Man",
          overview:
            "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
          poster_path: "/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [53, 80, 18],
          popularity: 11.2339,
          release_date: "2021-04-22",
          video: false,
          vote_average: 7.6,
          vote_count: 5817,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 1892,
      known_for_department: "Acting",
      name: "Matt Damon",
      original_name: "Matt Damon",
      popularity: 17.2228,
      profile_path: "/At3JgvaNeEN4Z4ESKlhhes85Xo3.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/sq8oUjbBvKkqv9h0Ns5rQbbquhZ.jpg",
          id: 286217,
          title: "The Martian",
          original_title: "The Martian",
          overview:
            "During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.",
          poster_path: "/3ndAx3weG6KDkJIRMCi5vXX6Dyb.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 12, 878],
          popularity: 11.2403,
          release_date: "2015-09-30",
          video: false,
          vote_average: 7.7,
          vote_count: 20604,
        },
        {
          adult: false,
          backdrop_path: "/bpV8wn48s82au37QyUJ51S7X2Vf.jpg",
          id: 489,
          title: "Good Will Hunting",
          original_title: "Good Will Hunting",
          overview:
            "Headstrong yet aimless, Will Hunting has a genius-level IQ but chooses to work as a janitor at MIT. When he secretly solves highly difficult graduate-level math problems, his talents are discovered by Professor Gerald Lambeau, who decides to help the misguided youth reach his potential. When Will is arrested for attacking a police officer, Professor Lambeau makes a deal to get leniency for him if he gets court-ordered therapy. Eventually, therapist Dr. Sean Maguire helps Will confront the demons that are holding him back.",
          poster_path: "/z2FnLKpFi1HPO7BEJxdkv6hpJSU.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18],
          popularity: 13.4099,
          release_date: "1997-12-05",
          video: false,
          vote_average: 8.2,
          vote_count: 13265,
        },
        {
          adult: false,
          backdrop_path: "/kJaRWmy1BGq3pHyE94LOTteiHer.jpg",
          id: 2501,
          title: "The Bourne Identity",
          original_title: "The Bourne Identity",
          overview:
            "Wounded to the brink of death and suffering from amnesia, Jason Bourne is rescued at sea by a fisherman. With nothing to go on but a Swiss bank account number, he starts to reconstruct his life, but finds that many people he encounters want him dead. However, Bourne realizes that he has the combat and mental skills of a world-class spy—but who does he work for?",
          poster_path: "/aP8swke3gmowbkfZ6lmNidu0y9p.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 18, 9648, 53],
          popularity: 8.0642,
          release_date: "2002-06-14",
          video: false,
          vote_average: 7.5,
          vote_count: 9738,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 1813,
      known_for_department: "Acting",
      name: "Anne Hathaway",
      original_name: "Anne Hathaway",
      popularity: 17.1613,
      profile_path: "/s6tflSD20MGz04ZR2R1lZvhmC4Y.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg",
          id: 157336,
          title: "Interstellar",
          original_title: "Interstellar",
          overview:
            "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
          poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [12, 18, 878],
          popularity: 35.7636,
          release_date: "2014-11-05",
          video: false,
          vote_average: 8.5,
          vote_count: 38272,
        },
        {
          adult: false,
          backdrop_path: "/3tWw50B1xXlCnJ9A7NX4nNzZF4j.jpg",
          id: 350,
          title: "The Devil Wears Prada",
          original_title: "The Devil Wears Prada",
          overview:
            "Andy moves to New York to work in the fashion industry. Her boss is extremely demanding, cruel and won't let her succeed if she doesn't fit into the high class elegant look of their magazine.",
          poster_path: "/8912AsVuS7Sj915apArUFbv6F9L.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 35],
          popularity: 13.1362,
          release_date: "2006-06-29",
          video: false,
          vote_average: 7.4,
          vote_count: 12610,
        },
        {
          adult: false,
          backdrop_path: "/n63e6JvKST0Gm222zolmhGb2ww6.jpg",
          id: 9880,
          title: "The Princess Diaries",
          original_title: "The Princess Diaries",
          overview:
            "A socially awkward but very bright 15-year-old girl being raised by a single mom discovers that she is the princess of a small European country because of the recent death of her long-absent father, who, unknown to her, was the crown prince of Genovia. She must make a choice between continuing the life of a San Francisco teen or stepping up to the throne.",
          poster_path: "/qSw4lzhDGeM5MjQc86BLzJALhBs.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 10751, 10749],
          popularity: 6.5107,
          release_date: "2001-08-03",
          video: false,
          vote_average: 7,
          vote_count: 5147,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 3455931,
      known_for_department: "Acting",
      name: "Truman Hanks",
      original_name: "Truman Hanks",
      popularity: 17.0328,
      profile_path: "/6ERfNyCNxGWnsTniEM8bfMk8TsL.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/9ZznETDyfPWVugRiv0jfGrkRftw.jpg",
          id: 937278,
          title: "A Man Called Otto",
          original_title: "A Man Called Otto",
          overview:
            "When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.",
          poster_path: "/130H1gap9lFfiTF9iDrqNIkFvC9.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [35, 18],
          popularity: 14.2636,
          release_date: "2022-12-28",
          video: false,
          vote_average: 7.756,
          vote_count: 3314,
        },
        {
          adult: false,
          backdrop_path: "/oIUDSK3CCqkpe6lct8YPuUupFes.jpg",
          id: 1172675,
          title: "The Swan",
          original_title: "The Swan",
          overview:
            "Two large, ignorant bullies ruthlessly pursue a small, brilliant boy in this young adult Roald Dahl short story.",
          poster_path: "/fRbx6DPdQBJrhZWyshjJABtAIyu.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18],
          popularity: 1.2361,
          release_date: "2023-09-27",
          video: false,
          vote_average: 6.8,
          vote_count: 482,
        },
        {
          adult: false,
          backdrop_path: "/57dG6BzU2RcPtLgoA3oyHUIb2rI.jpg",
          id: 581032,
          title: "News of the World",
          original_title: "News of the World",
          overview:
            "A Texan traveling across the wild West bringing the news of the world to local townspeople, agrees to help rescue a young girl who was kidnapped.",
          poster_path: "/fYQCgVRsQTEfUrP7cW5iAFVYOlh.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 37, 12],
          popularity: 6.4635,
          release_date: "2020-12-25",
          video: false,
          vote_average: 6.9,
          vote_count: 1855,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 2049994,
      known_for_department: "Acting",
      name: "Zhao Lusi",
      original_name: "赵露思",
      popularity: 16.8904,
      profile_path: "/y82wmaDqTdXqvtasb4kxAIuT44U.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/8wDXwRrj7lf0jtd7s1GqH8itrkm.jpg",
          id: 210733,
          name: "Hidden Love",
          original_name: "偷偷藏不住",
          overview:
            "Since high school, Sang Zhi has had a crush on Duan Jiaxu. When fate brings them together again, they find a chance to embark on a sweet relationship.",
          poster_path: "/riGzESa9N9toumP9OhMmg0QvFPD.jpg",
          media_type: "tv",
          original_language: "zh",
          genre_ids: [18],
          popularity: 15.9692,
          first_air_date: "2023-06-20",
          vote_average: 8.505,
          vote_count: 208,
          origin_country: ["CN"],
        },
        {
          adult: false,
          backdrop_path: "/5BuVAlwQiLHVqTWITHxaLmp2leB.jpg",
          id: 87299,
          name: "I Hear You",
          original_name: "最动听的事",
          overview:
            "Bei Er Duo, a girl from an ordinary family, dreams about studying in Japan to be a professional voice actor. However, her mother wants her to marry rich whilst she is young, leading to continuous blind dates which irritate Bei Er Duo. In her desperation to raise funds for studying overseas as well as helping her best friend Tang Li out of a crisis, Bei Er Duo joins a couple reality program, encountering top violin maker Ye Shu Wei.",
          poster_path: "/2wVMh3vqvt1IgAhextxwUKxaOAH.jpg",
          media_type: "tv",
          original_language: "zh",
          genre_ids: [18],
          popularity: 2.5199,
          first_air_date: "2019-01-28",
          vote_average: 7.7,
          vote_count: 68,
          origin_country: ["CN"],
        },
        {
          adult: false,
          backdrop_path: "/8MD7C9eznbwSxWljA8BE33B3YGl.jpg",
          id: 103635,
          name: "The Romance of Tiger and Rose",
          original_name: "传闻中的陈芊芊",
          overview:
            "Chen Xiaoqian, a struggling screenwriter suddenly finds herself trapped inside her own script as the Third Princess of Dongliang, a female-led kingdom. With her character caught between an arranged engagement to the noble Pei Heng and a forbidden love for Prince Han Shuo of a rival nation, Xiaoqian must rewrite her fate to survive—and discover what love truly means.",
          poster_path: "/mCsidkxf6ji8e71T07dYff3FjCF.jpg",
          media_type: "tv",
          original_language: "zh",
          genre_ids: [35, 18],
          popularity: 2.7495,
          first_air_date: "2020-05-18",
          vote_average: 7.385,
          vote_count: 26,
          origin_country: ["CN"],
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 865,
      known_for_department: "Directing",
      name: "Michael Bay",
      original_name: "Michael Bay",
      popularity: 16.2858,
      profile_path: "/rkC7lei20x5xlFH4SivAXXBh6uR.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/77P56ZcL8M9Cw7FIptMIGjhNJoj.jpg",
          id: 1858,
          title: "Transformers",
          original_title: "Transformers",
          overview:
            "Young teenager Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots – the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it.",
          poster_path: "/1P7w3AImoEOWJX7nn3fdaKDfEQA.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [12, 878, 28],
          popularity: 3.3379,
          release_date: "2007-06-27",
          video: false,
          vote_average: 6.8,
          vote_count: 11849,
        },
        {
          adult: false,
          backdrop_path: "/bH1bhjn37uA1zOPvyHbzJSvza7v.jpg",
          id: 8373,
          title: "Transformers: Revenge of the Fallen",
          original_title: "Transformers: Revenge of the Fallen",
          overview:
            "Sam Witwicky leaves the Autobots behind for a normal life. But when his mind is filled with cryptic symbols, the Decepticons target him and he is dragged back into the Transformers' war.",
          poster_path: "/pLBb0whOzVDtJvyD4DPeQyQNOqp.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [878, 28, 12],
          popularity: 3.0449,
          release_date: "2009-06-19",
          video: false,
          vote_average: 6.2,
          vote_count: 8917,
        },
        {
          adult: false,
          backdrop_path: "/x2sSPVVKFt20vzHDwOWJK1UUfSj.jpg",
          id: 38356,
          title: "Transformers: Dark of the Moon",
          original_title: "Transformers: Dark of the Moon",
          overview:
            "The Autobots continue to work for NEST, now no longer in secret. But after discovering a strange artifact during a mission in Chernobyl, it becomes apparent to Optimus Prime that the United States government has been less than forthright with them.",
          poster_path: "/28YlCLrFhONteYSs9hKjD1Km0Cj.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 878, 12],
          popularity: 2.8721,
          release_date: "2011-06-28",
          video: false,
          vote_average: 6.2,
          vote_count: 8697,
        },
      ],
    },
    {
      adult: false,
      gender: 1,
      id: 6194,
      known_for_department: "Acting",
      name: "Claire Danes",
      original_name: "Claire Danes",
      popularity: 16.22,
      profile_path: "/6YvMc6RViFSornxmZjRgEKWQMzI.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/m0miV65ZZIp13TNHJSRUF6vmCos.jpg",
          id: 454,
          title: "Romeo + Juliet",
          original_title: "Romeo + Juliet",
          overview:
            "In director Baz Luhrmann's contemporary take on William Shakespeare's classic tragedy, the Montagues and Capulets have moved their ongoing feud to the sweltering suburb of Verona Beach, where Romeo and Juliet fall in love and secretly wed. Though the film is visually modern, the bard's dialogue remains.",
          poster_path: "/eLf4jclPijOqfEp6bDAmezRFxk5.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [18, 10749],
          popularity: 5.5584,
          release_date: "1996-11-01",
          video: false,
          vote_average: 6.8,
          vote_count: 5193,
        },
        {
          adult: false,
          backdrop_path: "/391ixi0wVbFtFLQnOy8ZncWv2io.jpg",
          id: 1407,
          name: "Homeland",
          original_name: "Homeland",
          overview:
            "CIA officer Carrie Mathison is tops in her field despite being bipolar, which makes her volatile and unpredictable. With the help of her long-time mentor Saul Berenson, Carrie fearlessly risks everything, including her personal well-being and even sanity, at every turn.",
          poster_path: "/6GAvS2e6VIRsms9FpVt33PsCoEW.jpg",
          media_type: "tv",
          original_language: "en",
          genre_ids: [18, 10768, 80],
          popularity: 51.0981,
          first_air_date: "2011-10-02",
          vote_average: 7.6,
          vote_count: 2414,
          origin_country: ["US"],
        },
        {
          adult: false,
          backdrop_path: "/kbXMOnz2RhTSAbLtHX5hy5AXtwv.jpg",
          id: 296,
          title: "Terminator 3: Rise of the Machines",
          original_title: "Terminator 3: Rise of the Machines",
          overview:
            "It's been 10 years since John Connor saved Earth from Judgment Day, and he's now living under the radar, steering clear of using anything Skynet can trace. That is, until he encounters T-X, a robotic assassin ordered to finish what T-1000 started. Good thing Connor's former nemesis, the Terminator, is back to aid the now-adult Connor … just like he promised.",
          poster_path: "/vvevzdYIrk2636maNW4qeWmlPFG.jpg",
          media_type: "movie",
          original_language: "en",
          genre_ids: [28, 53, 878],
          popularity: 6.7958,
          release_date: "2003-07-02",
          video: false,
          vote_average: 6.2,
          vote_count: 6997,
        },
      ],
    },
  ],
  total_pages: 219447,
  total_results: 4388937,
};
